packages:
  - "packages/web"
  - "packages/devices/ts"
  - "packages/classroom-protocol"
  - "packages/classroom-server"
  - "packages/classroom-server-worker"
  - "packages/desktop"
  - "packages/plugin-sdk"
  - "packages/plugins/*"
  - "packages/cli-npm"
  - "packages/cli-npm-8085"
  - "packages/desktop-8085"
  - "packages/cli-npm-8051"
